version: '3.8'

services:
  data_pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: parliament_pipeline
    volumes:
      - .:/app

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: parliament_api
    ports:
      - "8000:8000"
    volumes:
      - ./parliament-search/src:/app/src
      - ./parliament-search/public:/app/public
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      data_pipeline:
        condition: service_completed_successfully

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: parliament_web
    ports:
      - "5173:5173"
    volumes:
      - ./parliament-search:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api